# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       profilematic

# >> macros
# << macros

Summary:    Automatic Profile changer
Version:    2.2.2
Release:    1
Group:      Applications/System
License:    GPL v3
URL:        https://github.com/ajalkane/profilematic
Source0:    %{name}-%{version}.tar.bz2
Source100:  profilematic.yaml
Requires:   qt-components
Requires:   mapplauncherd-booster-qtcomponents
Requires:   qt-mobility
Requires:   qmsystem
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(qdeclarative-boostable)
BuildRequires:  pkgconfig(qmsystem2)
BuildRequires:  pkgconfig(QtConnectivity)
BuildRequires:  pkgconfig(QtSystemInfo)
BuildRequires:  desktop-file-utils

%description
Changes phone's profile according to rules specified by user. At the moment supports rules based on time, location, and connected WLAN.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/profilematic
%{_datadir}/applications/profilematic.desktop
# >> files
# << files
