# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       profilematic

# >> macros
# << macros

Summary:    Automatic Profile changer
Version:    2.2.2
Release:    1
Group:      Applications/System
License:    GPL v3
URL:        https://github.com/ajalkane/profilematic
Source0:    %{name}-%{version}.tar.bz2
Source100:  profilematic.yaml
Requires:   qt-components
Requires:   mapplauncherd-booster-qtcomponents
Requires:   qt-mobility
Requires:   qmsystem
Requires:   libaccounts-qt
Requires:   dbus
Requires:   dbus-glib
Requires:   telepathy-qt4
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(qdeclarative-boostable)
BuildRequires:  pkgconfig(qmsystem2)
BuildRequires:  pkgconfig(QtConnectivity)
BuildRequires:  pkgconfig(QtSystemInfo)
BuildRequires:  pkgconfig(accounts-qt)
BuildRequires:  pkgconfig(TelepathyQt4)
BuildRequires:  pkgconfig(libmkcal)
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  pkgconfig(dbus-glib-1)
BuildRequires:  desktop-file-utils

%description
Changes phone's profile according to rules specified by user. At the moment supports rules based on time, location, and connected WLAN.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake  \
    MEEGO_VERSION_MAJOR=1 \ MEEGO_VERSION_MINOR=2 \ MEEGO_VERSION_PATCH=0 \ MEEGO_EDITION=harmattan \ MEEGO_SUBEDITION=nemo \ CONFIG+=platform_nemo DEFINES+=MEEGO_EDITION_HARMATTAN \ DEFINES+=CELLULAR_NOT_SUPPORTED \ DEFINES+=MEEGO_SUBEDITION_NEMO

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
/usr/share/applications/%{name}_harmattan.desktop
/opt/%{name}
/usr/share/icons/hicolor/*/apps/%{name}80.png
# >> files
# << files
